name: "Terraform Apply Workflow"

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      AWS_REGION_DEFAULT:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      CLUSTER_NAME:
        required: true
      FASTFOOD_APP_URL:
        required: true
jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION_DEFAULT }}
      
      - name: Terraform Init
        run: cd infra && terraform init

      - name: Terraform Plan
        run: cd infra && terraform plan -var "accountIdVoclabs=${{ secrets.AWS_ACCOUNT_ID }}" -var "fastfoodAppUrl=${{ secrets.FASTFOOD_APP_URL}}"

      - name: Terraform Apply
        run: cd infra && terraform apply -auto-approve -var "accountIdVoclabs=${{ secrets.AWS_ACCOUNT_ID }}" -var "fastfoodAppUrl=${{ secrets.FASTFOOD_APP_URL}}"
